#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop dashcam-transporter >/dev/null 2>&1 || true
  systemctl disable dashcam-transporter >/dev/null 2>&1 || true
fi

exit 0
